# Generated by Django 3.1.5 on 2021-01-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_header', models.CharField(max_length=500)),
                ('article_body', models.CharField(max_length=10000)),
                ('article_priority', models.IntegerField()),
                ('article_uploaded_date_time', models.DateTimeField(auto_now=True)),
                ('uploader_ip_address', models.GenericIPAddressField()),
                ('carousel_image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S')),
                ('image1', models.ImageField(upload_to='images/%Y/%m/%d/%H%M%S')),
                ('image2', models.ImageField(upload_to='images/%Y/%m/%d/%H%M%S')),
                ('image3', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S')),
                ('image4', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S')),
                ('image5', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S')),
                ('image6', models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S')),
                ('image7', models.ImageField(upload_to='images/%Y/%m/%d/%H%M%S')),
            ],
        ),
    ]
