# Generated by Django 3.1.5 on 2021-01-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_body',
            field=models.TextField(max_length=10000),
        ),
    ]
