# Generated by Django 3.1.5 on 2021-01-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210123_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_priority',
            field=models.IntegerField(blank=True),
        ),
    ]
