# Generated by Django 3.1.5 on 2021-01-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210123_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='active_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='carousel_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='trending_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image7',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='uploader_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
