# Generated by Django 3.1.5 on 2021-01-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210123_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image1',
            field=models.ImageField(upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S'),
        ),
    ]
