# Generated by Django 3.1.5 on 2021-01-23 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210123_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='image1',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image5',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image6',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='image7',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/%H%M%S', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
