# Generated by Django 3.1.5 on 2021-01-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210123_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='uploader_ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
