# Generated by Django 3.1.5 on 2021-01-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210129_0516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'permissions': (('can_edit_news', 'Can edit news'), ('can_view_news', 'Can view news'), ('can_delete_news', 'Can delete news'), ('can_upload_news', 'Can delete news'))},
        ),
    ]
