# Generated by Django 3.1.5 on 2021-01-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210130_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'permissions': (('can_edit_news', 'Can edit news1'),)},
        ),
    ]
