# Generated by Django 3.1.5 on 2021-01-29 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20210130_0454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'permissions': (('can_edit_news', 'Can edit news'), ('can_delete_news', 'Can delete news'), ('can_view_news', 'Can view news'), ('can_upload_news', 'Can upload news'))},
        ),
    ]
