# Generated by Django 3.1.5 on 2021-01-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20210130_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='article_category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('TECHNOLOGY', 'Technology'), ('POLITICS', 'Politics'), ('HISTORY', 'History'), ('SCIENCE', 'Science'), ('AERONAUTICS', 'Aeronautics')], default='General', max_length=500),
        ),
    ]
