# Generated by Django 3.1.5 on 2021-01-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_articlemodel_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article_category',
            field=models.CharField(choices=[('General', 'General'), ('Technology', 'Technology'), ('Politics', 'Politics'), ('History', 'History'), ('Science', 'Science'), ('Aeronautics', 'Aeronautics')], default='General', max_length=500),
        ),
    ]
