# Generated by Django 3.1.5 on 2021-01-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20210130_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='article_views',
            field=models.IntegerField(default=0),
        ),
    ]
